### ISSUE TITLE
lzma deprecated options -si and -so

### ISSUE THREAD

**Issue by drsn00ker** [dev-zzo/router-tools#5]
Looks like lzma has moved on from using the -si and -so options, thus resulting in extracted files containing the lzma error message rather than the data. I gotta go learn python2 to see if I can fix these errors.

**Comment by dev-zzo** [comment]
Frankly, that code needs to be thrown out and replaced with python3 + lzma from its library. Python2 is dead.

**Comment by drsn00ker** [comment]
Just looked at your updated lzma function call again. For it to work for me, the 'd' needs to change to '-d' for lzma to accept it as decompress. Same for 'e' to '-e' 
lzma seem to want a dash in front of the letter....

**Comment by dev-zzo** [comment]
You are goddamn right. Should be fixed now.
